---
- name: DevOps Tools Setup (kubectl, Helm, Terraform, Go)
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/main.yaml

  tasks:
    - import_tasks: tasks/go.yaml
      tags: [go, golang]

    - import_tasks: tasks/podman.yaml
      tags: [podman, containers]

    - import_tasks: tasks/kubectl.yaml
      tags: [kubectl, kubernetes]

    - import_tasks: tasks/helm.yaml
      tags: [helm, kubernetes]

    - import_tasks: tasks/terraform.yaml
      tags: [terraform, iac]

    - import_tasks: tasks/azure-cli.yaml
      tags: [azure, cloud]

    - import_tasks: tasks/devops-completions.yaml
      tags: [completions]
